INVENTORY_EXPORT_COLUMNS = [
    ("item_numero", "ITEM"),
    ("cod_inventario", "CÓD. INV"),
    ("cod_esbye", "CÓD. ESBYE"),
    ("cuenta", "CUENTA"),
    ("cantidad", "CANT"),
    ("descripcion", "DESCRIPCIÓN"),
    ("marca", "MARCA"),
    ("modelo", "MODELO"),
    ("serie", "SERIE"),
    ("estado", "ESTADO"),
    ("ubicacion", "UBICACIÓN"),
    ("fecha_adquisicion", "FECHA DE ADQUISICIÓN"),
    ("valor", "VALOR"),
    ("usuario_final", "USUARIO FINAL"),
    ("observacion", "OBSERVACIÓN"),
    ("descripcion_esbye", "DESCRIPCIÓN"),
    ("marca_esbye", "MARCA"),
    ("modelo_esbye", "MODELO"),
    ("serie_esbye", "SERIE"),
    ("fecha_adquisicion_esbye", "FECHA"),
    ("valor_esbye", "VALOR"),
    ("ubicacion_esbye", "UBICACIÓN"),
    ("observacion_esbye", "OBSERVACIÓN"),
]

AREA_EXPORT_COLUMNS = [
    ("ubicacion", "UBICACIÓN"),
    ("ambiente_aprendizaje", "AMBIENTE APRENDIZAJE"),
    ("identificacion_ambiente", "IDENTIFICACIÓN AMBIENTE"),
    ("metros_cuadrados", "METROS CUADRADOS"),
    ("alto", "ALTO"),
    ("senaletica", "SEÑALÉTICA"),
    ("cod_senaletica", "CÓD. SEÑALÉTICA"),
    ("infraestructura_fisica", "INFRAESTRUCTURA FÍSICA"),
    ("estado_piso", "ESTADO PISO"),
    ("material_techo", "MATERIAL TECHO"),
    ("puerta", "PUERTA"),
    ("material_puerta", "MATERIAL PUERTA"),
    ("responsable_admin_id", "ID RESPONSABLE"),
    ("estado_paredes", "ESTADO PAREDES"),
    ("estado_techo", "ESTADO TECHO"),
    ("estado_puerta", "ESTADO PUERTA"),
    ("cerradura", "CERRADURA"),
    ("nivel_seguridad", "NIVEL DE SEGURIDAD"),
    ("sitio_profesor_mesa", "SITIO PROFESOR MESA"),
    ("sitio_profesor_silla", "SITIO PROFESOR SILLA"),
    ("pc_aula", "PC AULA"),
    ("proyector", "PROYECTOR"),
    ("pantalla_interactiva", "PANTALLA INTERACTIVA"),
    ("pupitres_cantidad", "CANTIDAD PUPITRES"),
    ("pupitres_funcionan", "PUPITRES FUNCIONAN"),
    ("pupitres_no_funcionan", "PUPITRES NO FUNCIONAN"),
    ("pizarra", "PIZARRA"),
    ("pizarra_estado", "ESTADO PIZARRA"),
    ("ventanas_cantidad", "CANTIDAD VENTANAS"),
    ("ventanas_funcionan", "VENTANAS FUNCIONAN"),
    ("ventanas_no_funcionan", "VENTANAS NO FUNCIONAN"),
    ("aa_cantidad", "CANTIDAD A/C"),
    ("aa_funcionan", "A/C FUNCIONAN"),
    ("aa_no_funcionan", "A/C NO FUNCIONAN"),
    ("ventiladores_cantidad", "CANTIDAD VENTILADORES"),
    ("ventiladores_funcionan", "VENTILADORES FUNCIONAN"),
    ("ventiladores_no_funcionan", "VENTILADORES NO FUNCIONAN"),
    ("wifi", "WIFI"),
    ("red_lan", "RED LAN"),
    ("red_lan_funcionan", "RED LAN FUNCIONAN"),
    ("red_lan_no_funcionan", "RED LAN NO FUNCIONAN"),
    ("red_inalambrica_cantidad", "CANT. RED INALÁMBRICA"),
    ("iluminacion_funcionan", "ILUMINACIÓN FUNCIONAN"),
    ("iluminacion_no_funcionan", "ILUMINACIÓN NO FUNCIONAN"),
    ("luminarias_cantidad", "CANTIDAD LUMINARIAS"),
    ("puntos_electricos", "PUNTOS ELÉCTRICOS"),
    ("puntos_electricos_funcionan", "PUNTOS ELÉC. FUNCIONAN"),
    ("puntos_electricos_no_funcionan", "PUNTOS ELÉC. NO FUNCIONAN"),
    ("puntos_electricos_cantidad", "CANT. PUNTOS ELÉCTRICOS"),
    ("capacidad_aulica", "CAPACIDAD ÁULICA"),
    ("capacidad_distanciamiento", "CAPACIDAD DISTANCIAMIENTO"),
    ("ambiente_apto_retorno", "AMBIENTE APTO RETORNO"),
    ("observaciones_detalle", "OBSERVACIONES DETALLE"),
]
